import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const read=f=>readFileSync(new URL('../'+f,import.meta.url),'utf8');
const c=vm.createContext({document:{documentElement:{},addEventListener(){}},localStorage:{getItem(){return 'en'},setItem(){}},
  sfSafeHttpUrl:value=>/^https?:\/\//.test(value||'')?value:'',SF_USER:{id:'buyer'}});
c.window=c;
for(const f of ['i18n.js','private-offers.js'])vm.runInContext(read(f),c);
const api=c.SFPrivateOffers;
assert.equal(api.totals(12,10).total,174.23);
assert.equal(api.totals(.01,1).total,34.86);
const q={id:'quote',message_id:7,buyer_id:'buyer',seller_id:'seller',product_name:'Product <script>alert(1)</script>',product_image:'javascript:alert(1)',quantity:10,unit_price:12,...api.totals(12,10),status:'pending',expires_at:'2099-01-01',notes:'<img onerror=bad>'};
let card=api.cardHTML(q);
assert(card.includes('data-offer-action="accept"'));
assert(!card.includes('data-offer-action="withdrawn"'));
assert(card.includes('&lt;script&gt;'));
assert(!card.includes('src="javascript:'));
assert(card.includes('&lt;img onerror=bad&gt;'));
c.SF_USER.id='seller';card=api.cardHTML(q);
assert(card.includes('data-offer-action="withdrawn"'));assert(!card.includes('data-offer-action="accept"'));
c.SF_USER.id='stranger';assert(!api.cardHTML(q).includes('data-offer-action='));
c.SF_USER.id='buyer';
for(const status of ['declined','withdrawn','accepted'])assert(!api.cardHTML({...q,status}).includes('data-offer-action='));
assert(!api.cardHTML({...q,expires_at:'2000-01-01'}).includes('data-offer-action='));
assert(api.cardHTML({...q,status:'accepted'}).includes('web-orders.html'));
assert(!api.cardHTML(q,true).includes('data-offer-action='));
let filtered;
c.sb={from(table){return {select(){return this},eq(key,value){filtered=[table,key,value];return Promise.resolve({data:[q]})}}}};
assert.equal((await api.load(2))['7'],q);
assert.deepEqual(filtered,['private_chat_offers','conversation_id',2]);
vm.runInContext(read('messages-service.js'),c);
c.SFPrivateOffers={load:id=>{assert.equal(id,2);return Promise.resolve({'7':q})}};
c.sb={from(table){assert.equal(table,'messages');return {select(){return this},eq(){return this},order(){return this},then(fn){return Promise.resolve({data:[{id:7,sender_id:'seller',body:'Private offer',created_at:'2026-09-14'}]}).then(fn)}}}};
const messages=await c.SFMessages.loadMessages(2);
assert.equal(messages[0].offer,q);assert.equal(messages[0].from,'theirs');
const html=read('web-messages.html');
for(const [i,match] of Array.from(html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)).entries())new vm.Script(match[1],{filename:'web-messages-inline-'+i});
console.log('PASS fee preview, offer rendering/escaping, role-specific actions, closed/expired offers, conversation filter, message enrichment, and page syntax');
