-- ============================================================
-- تقييمات المنتجات ومراجعات المشترين
-- ------------------------------------------------------------
-- من اشترى فعلاً وحده يقيّم (بطلب المالك): التقييم بلا شراء
-- يفتح الباب للمزيّف ولمهاجمة المنافسين، والقيد هنا في
-- الخادم لا في الواجهة — فلا يُتحايل عليه من المتصفّح.
--
-- وصاحب المصنع لا يملك تعليقات المشترين ولا تقييمهم (بطلب
-- المالك صريحاً): لا حذف ولا تعديل ولا إخفاء. وهذا ما يجعل
-- النجوم ذات معنى؛ ولو ملك حذفها لما بقي إلّا الخمس نجوم.
-- والحذف للمقيّم نفسه وللمشرف وحدهما.
--
-- يُطبَّق مرّة واحدة بترتيب اسم الملفّ:
-- Supabase → SQL Editor → New query → لصق → Run
-- ============================================================

-- 1) الجدول -------------------------------------------------
create table if not exists public.product_reviews (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references public.products(id) on delete cascade,
  author_id   uuid   not null references auth.users(id) on delete cascade,
  rating      smallint not null check (rating between 1 and 5),
  body        text   not null default '' check (length(body) <= 2000),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- مراجعة واحدة لكلّ مشترٍ لكلّ منتج: بلا هذا القيد يرفع
  -- المشتري الواحد تقييمَ منتجٍ بعشر مراجعات.
  unique (product_id, author_id)
);

create index if not exists product_reviews_product_idx
  on public.product_reviews (product_id, created_at desc);

create index if not exists product_reviews_author_idx
  on public.product_reviews (author_id);

-- 2) هل اشترى هذا المستخدم هذا المنتج؟ ----------------------
-- security definer لأنّ المشتري لا يملك حقّ قراءة صفوف
-- order_items لغيره، والدالّة تجيب بنعم أو لا فحسب.
create or replace function public.has_purchased_product(
  p_product_id bigint,
  p_user_id    uuid default auth.uid()
) returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select exists (
    select 1
      from public.order_items oi
      join public.orders o on o.id = oi.order_id
     where oi.product_id = p_product_id
       and o.buyer_id    = p_user_id
  );
$fn$;

revoke all on function public.has_purchased_product(bigint, uuid) from public;
grant execute on function public.has_purchased_product(bigint, uuid) to authenticated;

-- 3) RLS ----------------------------------------------------
alter table public.product_reviews enable row level security;

-- القراءة للجميع: المراجعات تُعرض للزائر قبل أن يسجّل،
-- وهي نصف فائدتها.
drop policy if exists product_reviews_read on public.product_reviews;
create policy product_reviews_read
  on public.product_reviews
  for select
  using (true);

-- الكتابة لمن اشترى وحده، وباسمه وحده.
drop policy if exists product_reviews_insert on public.product_reviews;
create policy product_reviews_insert
  on public.product_reviews
  for insert
  to authenticated
  with check (
    author_id = auth.uid()
    and public.has_purchased_product(product_id, auth.uid())
  );

-- التعديل لصاحب المراجعة وحده.
drop policy if exists product_reviews_update on public.product_reviews;
create policy product_reviews_update
  on public.product_reviews
  for update
  to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

-- الحذف لصاحبها أو للمشرف. وصاحب المصنع ليس فيهما عمداً:
-- طلب المالك ألّا يتحكّم المصنع بتعليقات المشترين.
drop policy if exists product_reviews_delete on public.product_reviews;
create policy product_reviews_delete
  on public.product_reviews
  for delete
  to authenticated
  using (author_id = auth.uid() or public.is_admin());

-- 4) حارس الأعمدة ------------------------------------------
-- with check يتحقّق «من» يكتب لا «ماذا» يكتب، فلا يمنع
-- المقيّم من تحويل مراجعته إلى منتج آخر أو تزوير تاريخها.
create or replace function public.product_reviews_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  -- لا نقل المراجعة إلى منتج آخر، ولا تغيير كاتبها
  new.product_id := old.product_id;
  new.author_id  := old.author_id;
  new.created_at := old.created_at;
  new.updated_at := now();
  return new;
end;
$fn$;

drop trigger if exists product_reviews_guard_trg on public.product_reviews;
create trigger product_reviews_guard_trg
  before update on public.product_reviews
  for each row execute function public.product_reviews_guard();

-- 5) ملخّص التقييم للعرض -----------------------------------
-- المتوسّط والعدد لمنتجات كثيرة في نداء واحد: البطاقات في
-- الصفحة الرئيسية أربع وعشرون، فحسابها صفّاً صفّاً أربعة
-- وعشرون نداءً.
create or replace function public.get_product_ratings(
  p_product_ids bigint[]
) returns table (
  product_id   bigint,
  rating_avg   numeric,
  rating_count bigint
)
language sql
stable
security definer
set search_path = public
as $fn$
  select r.product_id,
         round(avg(r.rating)::numeric, 2),
         count(*)
    from public.product_reviews r
   where r.product_id = any(p_product_ids)
   group by r.product_id;
$fn$;

revoke all on function public.get_product_ratings(bigint[]) from public;
grant execute on function public.get_product_ratings(bigint[]) to anon, authenticated;

-- 6) مراجعات منتج مع أسماء كاتبيها -------------------------
-- ضمّ profiles مباشرةً يُرفض: المشتري لا يملك قراءة صفوف
-- profiles لغيره، وRLS محقّ في منعه. فالدالّة تُرجِع الاسم
-- والصورة وحدهما.
create or replace function public.get_product_reviews(
  p_product_id bigint,
  p_limit      integer default 20,
  p_offset     integer default 0
) returns table (
  id           bigint,
  rating       smallint,
  body         text,
  created_at   timestamptz,
  author_name  text,
  author_image text,
  is_mine      boolean
)
language sql
stable
security definer
set search_path = public
as $fn$
  select r.id,
         r.rating,
         r.body,
         r.created_at,
         coalesce(nullif(p.full_name, ''), 'مشترٍ') as author_name,
         coalesce(p.company_image, '')              as author_image,
         (r.author_id = auth.uid())                 as is_mine
    from public.product_reviews r
    left join public.profiles p on p.id = r.author_id
   where r.product_id = p_product_id
   order by r.created_at desc
   limit  greatest(1, least(coalesce(p_limit, 20), 100))
   offset greatest(0, coalesce(p_offset, 0));
$fn$;

revoke all on function public.get_product_reviews(bigint, integer, integer) from public;
grant execute on function public.get_product_reviews(bigint, integer, integer) to anon, authenticated;

-- 7) هل يحقّ لي أن أقيّم هذا المنتج؟ ------------------------
-- الواجهة تسأل قبل أن تُظهر نموذج التقييم، فلا يكتب
-- المستخدم مراجعة ثمّ يُرفض عند الإرسال.
create or replace function public.can_review_product(
  p_product_id bigint
) returns table (
  can_review  boolean,
  has_review  boolean
)
language sql
stable
security definer
set search_path = public
as $fn$
  select public.has_purchased_product(p_product_id, auth.uid()),
         exists (
           select 1 from public.product_reviews r
            where r.product_id = p_product_id
              and r.author_id  = auth.uid()
         );
$fn$;

revoke all on function public.can_review_product(bigint) from public;
grant execute on function public.can_review_product(bigint) to authenticated;

-- 8) تحقّق ---------------------------------------------------
select 'product_reviews ready' as status,
       count(*)                as existing_reviews
  from public.product_reviews;
